version: '3.8'

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: 'postgres-${COMPOSE_PROJECT_NAME}'
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DATABASE}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - '${POSTGRES_PORT}:5432'
  # extra_hosts: # for docker on mac, it allows to use localhost
  #   - 'host.docker.internal:host-gateway'

  postgres_multi_database:
    image: postgres:latest
    restart: always
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5555:5432'

  adminer:
    image: adminer
    restart: always
    volumes:
      - ./docker-postgresql-multiple-databases:/adminer
    ports:
      - 5050:8080
